
package org.kuali.rice.kim.v2_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.kuali.rice.core.v2_0.QueryByCriteriaType;
import org.kuali.rice.core.v2_0.StringMapEntryListType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "groupService", targetNamespace = "http://rice.kuali.org/kim/v2_0")
@XmlSeeAlso({
    org.kuali.rice.core.v2_0.ObjectFactory.class,
    org.kuali.rice.kim.v2_0.ObjectFactory.class
})
public interface GroupService {


    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalIdResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getGroupIdsByPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalId")
    @ResponseWrapper(localName = "getGroupIdsByPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalIdResponse")
    public org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalIdResponse.GroupIds getGroupIdsByPrincipalId(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupMember
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "createGroupMember", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.CreateGroupMember")
    @ResponseWrapper(localName = "createGroupMemberResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.CreateGroupMemberResponse")
    public void createGroupMember(
        @WebParam(name = "groupMember", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<GroupMemberType> groupMember)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetMemberPrincipalIdsResponse.PrincipalIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getMemberPrincipalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMemberPrincipalIds")
    @ResponseWrapper(localName = "getMemberPrincipalIdsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMemberPrincipalIdsResponse")
    public org.kuali.rice.kim.v2_0.GetMemberPrincipalIdsResponse.PrincipalIds getMemberPrincipalIds(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @param namespaceCode
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetGroupsByPrincipalIdAndNamespaceCodeResponse.Groups
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groups", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getGroupsByPrincipalIdAndNamespaceCode", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupsByPrincipalIdAndNamespaceCode")
    @ResponseWrapper(localName = "getGroupsByPrincipalIdAndNamespaceCodeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupsByPrincipalIdAndNamespaceCodeResponse")
    public org.kuali.rice.kim.v2_0.GetGroupsByPrincipalIdAndNamespaceCodeResponse.Groups getGroupsByPrincipalIdAndNamespaceCode(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId,
        @WebParam(name = "namespaceCode", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String namespaceCode)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetDirectMemberPrincipalIdsResponse.PrincipalIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getDirectMemberPrincipalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectMemberPrincipalIds")
    @ResponseWrapper(localName = "getDirectMemberPrincipalIdsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectMemberPrincipalIdsResponse")
    public org.kuali.rice.kim.v2_0.GetDirectMemberPrincipalIdsResponse.PrincipalIds getDirectMemberPrincipalIds(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetDirectMemberOfGroupResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getDirectMemberOfGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectMemberOfGroup")
    @ResponseWrapper(localName = "getDirectMemberOfGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectMemberOfGroupResponse")
    public org.kuali.rice.kim.v2_0.GetDirectMemberOfGroupResponse.GroupIds getDirectMemberOfGroup(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param arg1
     * @param asOfDate
     * @param arg0
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "isMember", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "isGroupMemberOfGroupWithDate", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsGroupMemberOfGroupWithDate")
    @ResponseWrapper(localName = "isGroupMemberOfGroupWithDateResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsGroupMemberOfGroupWithDateResponse")
    public boolean isGroupMemberOfGroupWithDate(
        @WebParam(name = "arg0", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String arg1,
        @WebParam(name = "asOfDate", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        XMLGregorianCalendar asOfDate)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.kim.v2_0.FindGroupIdsResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findGroupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindGroupIds")
    @ResponseWrapper(localName = "findGroupIdsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindGroupIdsResponse")
    public org.kuali.rice.kim.v2_0.FindGroupIdsResponse.GroupIds findGroupIds(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.kim.v2_0.GroupQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findGroups", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindGroups")
    @ResponseWrapper(localName = "findGroupsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindGroupsResponse")
    public GroupQueryResultsType findGroups(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.core.v2_0.StringMapEntryListType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "attributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAttributesResponse")
    public StringMapEntryListType getAttributes(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetMembersOfGroupResponse.Members
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "members", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getMembersOfGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembersOfGroup")
    @ResponseWrapper(localName = "getMembersOfGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembersOfGroupResponse")
    public org.kuali.rice.kim.v2_0.GetMembersOfGroupResponse.Members getMembersOfGroup(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @param namespaceCode
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalIdAndNamespaceCodeResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getGroupIdsByPrincipalIdAndNamespaceCode", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalIdAndNamespaceCode")
    @ResponseWrapper(localName = "getGroupIdsByPrincipalIdAndNamespaceCodeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalIdAndNamespaceCodeResponse")
    public org.kuali.rice.kim.v2_0.GetGroupIdsByPrincipalIdAndNamespaceCodeResponse.GroupIds getGroupIdsByPrincipalIdAndNamespaceCode(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId,
        @WebParam(name = "namespaceCode", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String namespaceCode)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param group
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroupWithId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateGroupWithId")
    @ResponseWrapper(localName = "updateGroupWithIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateGroupWithIdResponse")
    public void updateGroupWithId(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId,
        @WebParam(name = "group", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<GroupType> group)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.GroupType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "group", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroup")
    @ResponseWrapper(localName = "getGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupResponse")
    public GroupType getGroup(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param asOfDate
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetMembersOfGroupWithDateResponse.Members
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "members", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getMembersOfGroupWithDate", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembersOfGroupWithDate")
    @ResponseWrapper(localName = "getMembersOfGroupWithDateResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembersOfGroupWithDateResponse")
    public org.kuali.rice.kim.v2_0.GetMembersOfGroupWithDateResponse.Members getMembersOfGroupWithDate(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId,
        @WebParam(name = "asOfDate", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        XMLGregorianCalendar asOfDate)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parentId
     * @param childId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "addedToGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "addGroupToGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddGroupToGroup")
    @ResponseWrapper(localName = "addGroupToGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddGroupToGroupResponse")
    public boolean addGroupToGroup(
        @WebParam(name = "childId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String childId,
        @WebParam(name = "parentId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String parentId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupIds
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetMembersResponse.Members
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "members", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getMembers", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembers")
    @ResponseWrapper(localName = "getMembersResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembersResponse")
    public org.kuali.rice.kim.v2_0.GetMembersResponse.Members getMembers(
        @WebParam(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        List<String> groupIds)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupMember
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroupMember", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateGroupMember")
    @ResponseWrapper(localName = "updateGroupMemberResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateGroupMemberResponse")
    public void updateGroupMember(
        @WebParam(name = "groupMember", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<GroupMemberType> groupMember)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "removeAllMembers", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.RemoveAllMembers")
    @ResponseWrapper(localName = "removeAllMembersResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.RemoveAllMembersResponse")
    public void removeAllMembers(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.kim.v2_0.GroupMemberQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findGroupMembers", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindGroupMembers")
    @ResponseWrapper(localName = "findGroupMembersResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindGroupMembersResponse")
    public GroupMemberQueryResultsType findGroupMembers(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetGroupsByPrincipalIdResponse.Groups
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groups", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getGroupsByPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupsByPrincipalId")
    @ResponseWrapper(localName = "getGroupsByPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupsByPrincipalIdResponse")
    public org.kuali.rice.kim.v2_0.GetGroupsByPrincipalIdResponse.Groups getGroupsByPrincipalId(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param principalId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "addedToGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "addPrincipalToGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrincipalToGroup")
    @ResponseWrapper(localName = "addPrincipalToGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrincipalToGroupResponse")
    public boolean addPrincipalToGroup(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId,
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetMemberGroupIdsResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getMemberGroupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMemberGroupIds")
    @ResponseWrapper(localName = "getMemberGroupIdsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMemberGroupIdsResponse")
    public org.kuali.rice.kim.v2_0.GetMemberGroupIdsResponse.GroupIds getMemberGroupIds(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param groupMemberId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "isMember", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "isGroupMemberOfGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsGroupMemberOfGroup")
    @ResponseWrapper(localName = "isGroupMemberOfGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsGroupMemberOfGroupResponse")
    public boolean isGroupMemberOfGroup(
        @WebParam(name = "groupMemberId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupMemberId,
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param principalId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "isDirectMember", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "isDirectMemberOfGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsDirectMemberOfGroup")
    @ResponseWrapper(localName = "isDirectMemberOfGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsDirectMemberOfGroupResponse")
    public boolean isDirectMemberOfGroup(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId,
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param arg1
     * @param asOfDate
     * @param arg0
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "isMember", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "isMemberOfGroupWithDate", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsMemberOfGroupWithDate")
    @ResponseWrapper(localName = "isMemberOfGroupWithDateResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsMemberOfGroupWithDateResponse")
    public boolean isMemberOfGroupWithDate(
        @WebParam(name = "arg0", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String arg1,
        @WebParam(name = "asOfDate", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        XMLGregorianCalendar asOfDate)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param principalId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "isMember", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "isMemberOfGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsMemberOfGroup")
    @ResponseWrapper(localName = "isMemberOfGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.IsMemberOfGroupResponse")
    public boolean isMemberOfGroup(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId,
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parentId
     * @param childId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "removedFromGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "removeGroupFromGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.RemoveGroupFromGroup")
    @ResponseWrapper(localName = "removeGroupFromGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.RemoveGroupFromGroupResponse")
    public boolean removeGroupFromGroup(
        @WebParam(name = "childId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String childId,
        @WebParam(name = "parentId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String parentId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param group
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateGroup")
    @ResponseWrapper(localName = "updateGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateGroupResponse")
    public void updateGroup(
        @WebParam(name = "group", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<GroupType> group)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetDirectGroupIdsByPrincipalIdResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getDirectGroupIdsByPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectGroupIdsByPrincipalId")
    @ResponseWrapper(localName = "getDirectGroupIdsByPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectGroupIdsByPrincipalIdResponse")
    public org.kuali.rice.kim.v2_0.GetDirectGroupIdsByPrincipalIdResponse.GroupIds getDirectGroupIdsByPrincipalId(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param asOfDate
     * @param arg0
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetDirectParentGroupIdsWithDateResponse.DirectParents
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "directParents", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getDirectParentGroupIdsWithDate", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectParentGroupIdsWithDate")
    @ResponseWrapper(localName = "getDirectParentGroupIdsWithDateResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectParentGroupIdsWithDateResponse")
    public org.kuali.rice.kim.v2_0.GetDirectParentGroupIdsWithDateResponse.DirectParents getDirectParentGroupIdsWithDate(
        @WebParam(name = "arg0", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String arg0,
        @WebParam(name = "asOfDate", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        XMLGregorianCalendar asOfDate)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetDirectParentGroupIdsResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getDirectParentGroupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectParentGroupIds")
    @ResponseWrapper(localName = "getDirectParentGroupIdsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectParentGroupIdsResponse")
    public org.kuali.rice.kim.v2_0.GetDirectParentGroupIdsResponse.GroupIds getDirectParentGroupIds(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetDirectMemberGroupIdsWithDateResponse.DirectMembers
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "directMembers", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getDirectMemberGroupIdsWithDate", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectMemberGroupIdsWithDate")
    @ResponseWrapper(localName = "getDirectMemberGroupIdsWithDateResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDirectMemberGroupIdsWithDateResponse")
    public org.kuali.rice.kim.v2_0.GetDirectMemberGroupIdsWithDateResponse.DirectMembers getDirectMemberGroupIdsWithDate(
        @WebParam(name = "arg0", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String arg0)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param principalId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "removedFromGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "removePrincipalFromGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.RemovePrincipalFromGroup")
    @ResponseWrapper(localName = "removePrincipalFromGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.RemovePrincipalFromGroupResponse")
    public boolean removePrincipalFromGroup(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId,
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param asOfDate
     * @param arg0
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetMembersWithDateResponse.Members
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "members", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getMembersWithDate", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembersWithDate")
    @ResponseWrapper(localName = "getMembersWithDateResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMembersWithDateResponse")
    public org.kuali.rice.kim.v2_0.GetMembersWithDateResponse.Members getMembersWithDate(
        @WebParam(name = "arg0", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        List<String> arg0,
        @WebParam(name = "asOfDate", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        XMLGregorianCalendar asOfDate)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param group
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "createGroup", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.CreateGroup")
    @ResponseWrapper(localName = "createGroupResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.CreateGroupResponse")
    public void createGroup(
        @WebParam(name = "group", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<GroupType> group)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param ids
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetGroupsResponse.Groups
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groups", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getGroups", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroups")
    @ResponseWrapper(localName = "getGroupsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupsResponse")
    public org.kuali.rice.kim.v2_0.GetGroupsResponse.Groups getGroups(
        @WebParam(name = "ids", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        List<String> ids)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupName
     * @param namespaceCode
     * @return
     *     returns org.kuali.rice.kim.v2_0.GroupType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "group", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getGroupByNamespaceCodeAndName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupByNamespaceCodeAndName")
    @ResponseWrapper(localName = "getGroupByNamespaceCodeAndNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetGroupByNamespaceCodeAndNameResponse")
    public GroupType getGroupByNamespaceCodeAndName(
        @WebParam(name = "namespaceCode", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String namespaceCode,
        @WebParam(name = "groupName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetParentGroupIdsResponse.GroupIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getParentGroupIds", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetParentGroupIds")
    @ResponseWrapper(localName = "getParentGroupIdsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetParentGroupIdsResponse")
    public org.kuali.rice.kim.v2_0.GetParentGroupIdsResponse.GroupIds getParentGroupIds(
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String groupId)
        throws RiceIllegalArgumentException
    ;

}
