
package org.kuali.rice.kim.v2_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.kuali.rice.core.v2_0.QueryByCriteriaType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "identityService", targetNamespace = "http://rice.kuali.org/kim/v2_0")
@XmlSeeAlso({
    org.kuali.rice.core.v2_0.ObjectFactory.class,
    org.kuali.rice.kim.v2_0.ObjectFactory.class
})
public interface IdentityService {


    /**
     * 
     * @param residency
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addResidencyToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddResidencyToEntity")
    @ResponseWrapper(localName = "addResidencyToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddResidencyToEntityResponse")
    public void addResidencyToEntity(
        @WebParam(name = "residency", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityResidencyType> residency)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param address
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateAddress", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAddress")
    @ResponseWrapper(localName = "updateAddressResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAddressResponse")
    public void updateAddress(
        @WebParam(name = "address", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityAddressType> address)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param visa
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addVisaToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddVisaToEntity")
    @ResponseWrapper(localName = "addVisaToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddVisaToEntityResponse")
    public void addVisaToEntity(
        @WebParam(name = "visa", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityVisaType> visa)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param name
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addNameToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddNameToEntity")
    @ResponseWrapper(localName = "addNameToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddNameToEntityResponse")
    public void addNameToEntity(
        @WebParam(name = "name", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityNameType> name)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.EntityAffiliationTypeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllAffiliationTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAffiliationTypes")
    @ResponseWrapper(localName = "findAllAffiliationTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAffiliationTypesResponse")
    public List<EntityAffiliationTypeType> findAllAffiliationTypes();

    /**
     * 
     * @param employment
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmployment", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmployment")
    @ResponseWrapper(localName = "updateEmploymentResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmploymentResponse")
    public void updateEmployment(
        @WebParam(name = "employment", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityEmploymentType> employment)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param principal
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updatePrincipal", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePrincipal")
    @ResponseWrapper(localName = "updatePrincipalResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePrincipalResponse")
    public void updatePrincipal(
        @WebParam(name = "principal", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<PrincipalType> principal)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param entity
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEntity")
    @ResponseWrapper(localName = "updateEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEntityResponse")
    public void updateEntity(
        @WebParam(name = "entity", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityType> entity)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllNameTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllNameTypes")
    @ResponseWrapper(localName = "findAllNameTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllNameTypesResponse")
    public List<CodedAttributeType> findAllNameTypes();

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getAddressType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAddressType")
    @ResponseWrapper(localName = "getAddressTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAddressTypeResponse")
    public CodedAttributeType getAddressType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalName
     * @return
     *     returns org.kuali.rice.kim.v2_0.PrincipalType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivatePrincipalByName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePrincipalByName")
    @ResponseWrapper(localName = "inactivatePrincipalByNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePrincipalByNameResponse")
    public PrincipalType inactivatePrincipalByName(
        @WebParam(name = "principalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalName)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param externalId
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateExternalIdentifier", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateExternalIdentifier")
    @ResponseWrapper(localName = "updateExternalIdentifierResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateExternalIdentifierResponse")
    public void updateExternalIdentifier(
        @WebParam(name = "externalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityExternalIdentifierType> externalId)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param affiliation
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addAffiliationToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAffiliationToEntity")
    @ResponseWrapper(localName = "addAffiliationToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAffiliationToEntityResponse")
    public void addAffiliationToEntity(
        @WebParam(name = "affiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityAffiliationType> affiliation)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityDefaultType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entityDefault", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityDefaultByPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefaultByPrincipalId")
    @ResponseWrapper(localName = "getEntityDefaultByPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefaultByPrincipalIdResponse")
    public EntityDefaultType getEntityDefaultByPrincipalId(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getPhoneType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPhoneType")
    @ResponseWrapper(localName = "getPhoneTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPhoneTypeResponse")
    public CodedAttributeType getPhoneType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityEmploymentType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "employment", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateEmployment", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmployment")
    @ResponseWrapper(localName = "inactivateEmploymentResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmploymentResponse")
    public EntityEmploymentType inactivateEmployment(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.PrincipalType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivatePrincipal", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePrincipal")
    @ResponseWrapper(localName = "inactivatePrincipalResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePrincipalResponse")
    public PrincipalType inactivatePrincipal(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEmploymentType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentType")
    @ResponseWrapper(localName = "getEmploymentTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentTypeResponse")
    public CodedAttributeType getEmploymentType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityNamePrincipalNameType
     */
    @WebMethod
    @WebResult(name = "entityNamePrincipalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getDefaultNamesForPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDefaultNamesForPrincipalId")
    @ResponseWrapper(localName = "getDefaultNamesForPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDefaultNamesForPrincipalIdResponse")
    public EntityNamePrincipalNameType getDefaultNamesForPrincipalId(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId);

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.kim.v2_0.PrincipalQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findPrincipals", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindPrincipals")
    @ResponseWrapper(localName = "findPrincipalsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindPrincipalsResponse")
    public PrincipalQueryResultsType findPrincipals(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityCitizenshipType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "citizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateCitizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateCitizenship")
    @ResponseWrapper(localName = "inactivateCitizenshipResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateCitizenshipResponse")
    public EntityCitizenshipType inactivateCitizenship(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEmailType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmailType")
    @ResponseWrapper(localName = "getEmailTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmailTypeResponse")
    public CodedAttributeType getEmailType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalName
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityByPrincipalName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityByPrincipalName")
    @ResponseWrapper(localName = "getEntityByPrincipalNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityByPrincipalNameResponse")
    public EntityType getEntityByPrincipalName(
        @WebParam(name = "principalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findEntities", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntities")
    @ResponseWrapper(localName = "findEntitiesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntitiesResponse")
    public EntityQueryResultsType findEntities(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param entityTypeCode
     * @param entityId
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityTypeContactInfoType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entityTypeContactInfo", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateEntityTypeContactInfo", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEntityTypeContactInfo")
    @ResponseWrapper(localName = "inactivateEntityTypeContactInfoResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEntityTypeContactInfoResponse")
    public EntityTypeContactInfoType inactivateEntityTypeContactInfo(
        @WebParam(name = "entityId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String entityId,
        @WebParam(name = "entityTypeCode", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String entityTypeCode)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param citizenship
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateCitizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateCitizenship")
    @ResponseWrapper(localName = "updateCitizenshipResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateCitizenshipResponse")
    public void updateCitizenship(
        @WebParam(name = "citizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityCitizenshipType> citizenship)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityAffiliationType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "affiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateAffiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAffiliation")
    @ResponseWrapper(localName = "inactivateAffiliationResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAffiliationResponse")
    public EntityAffiliationType inactivateAffiliation(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getCitizenshipStatus", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetCitizenshipStatus")
    @ResponseWrapper(localName = "getCitizenshipStatusResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetCitizenshipStatusResponse")
    public CodedAttributeType getCitizenshipStatus(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityDefaultQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findEntityDefaults", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntityDefaults")
    @ResponseWrapper(localName = "findEntityDefaultsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntityDefaultsResponse")
    public EntityDefaultQueryResultsType findEntityDefaults(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param email
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addEmailToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmailToEntity")
    @ResponseWrapper(localName = "addEmailToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmailToEntityResponse")
    public void addEmailToEntity(
        @WebParam(name = "email", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityEmailType> email)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param residency
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateResidency", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateResidency")
    @ResponseWrapper(localName = "updateResidencyResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateResidencyResponse")
    public void updateResidency(
        @WebParam(name = "residency", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityResidencyType> residency)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param principalName
     * @return
     *     returns org.kuali.rice.kim.v2_0.PrincipalType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getPrincipalByPrincipalName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalByPrincipalName")
    @ResponseWrapper(localName = "getPrincipalByPrincipalNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalByPrincipalNameResponse")
    public PrincipalType getPrincipalByPrincipalName(
        @WebParam(name = "principalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityAffiliationTypeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "affiliationType", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getAffiliationType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAffiliationType")
    @ResponseWrapper(localName = "getAffiliationTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAffiliationTypeResponse")
    public EntityAffiliationTypeType getAffiliationType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityExternalIdentifierTypeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getExternalIdentifierType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetExternalIdentifierType")
    @ResponseWrapper(localName = "getExternalIdentifierTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetExternalIdentifierTypeResponse")
    public EntityExternalIdentifierTypeType getExternalIdentifierType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityType")
    @ResponseWrapper(localName = "getEntityTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityTypeResponse")
    public CodedAttributeType getEntityType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param privacyPreferences
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addPrivacyPreferencesToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrivacyPreferencesToEntity")
    @ResponseWrapper(localName = "addPrivacyPreferencesToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrivacyPreferencesToEntityResponse")
    public void addPrivacyPreferencesToEntity(
        @WebParam(name = "privacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityPrivacyPreferencesType> privacyPreferences)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param ethnicity
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addEthnicityToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEthnicityToEntity")
    @ResponseWrapper(localName = "addEthnicityToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEthnicityToEntityResponse")
    public void addEthnicityToEntity(
        @WebParam(name = "ethnicity", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityEthnicityType> ethnicity)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntity")
    @ResponseWrapper(localName = "getEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityResponse")
    public EntityType getEntity(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param entityId
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.PrincipalType>
     */
    @WebMethod
    @WebResult(name = "principals", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getPrincipalsByEntityId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEntityId")
    @ResponseWrapper(localName = "getPrincipalsByEntityIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEntityIdResponse")
    public List<PrincipalType> getPrincipalsByEntityId(
        @WebParam(name = "entityId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String entityId);

    /**
     * 
     * @param employeeId
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.PrincipalType>
     */
    @WebMethod
    @WebResult(name = "principals", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getPrincipalsByEmployeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEmployeeId")
    @ResponseWrapper(localName = "getPrincipalsByEmployeeIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEmployeeIdResponse")
    public List<PrincipalType> getPrincipalsByEmployeeId(
        @WebParam(name = "employeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String employeeId);

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getNameType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetNameType")
    @ResponseWrapper(localName = "getNameTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetNameTypeResponse")
    public CodedAttributeType getNameType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalName
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityDefaultType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entityDefault", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityDefaultByPrincipalName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefaultByPrincipalName")
    @ResponseWrapper(localName = "getEntityDefaultByPrincipalNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefaultByPrincipalNameResponse")
    public EntityDefaultType getEntityDefaultByPrincipalName(
        @WebParam(name = "principalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityNameType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "name", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateName")
    @ResponseWrapper(localName = "inactivateNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateNameResponse")
    public EntityNameType inactivateName(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param email
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmail", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmail")
    @ResponseWrapper(localName = "updateEmailResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmailResponse")
    public void updateEmail(
        @WebParam(name = "email", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityEmailType> email)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllAddressTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAddressTypes")
    @ResponseWrapper(localName = "findAllAddressTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAddressTypesResponse")
    public List<CodedAttributeType> findAllAddressTypes();

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityAddressType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "address", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateAddress", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAddress")
    @ResponseWrapper(localName = "inactivateAddressResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAddressResponse")
    public EntityAddressType inactivateAddress(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param privacyPreferences
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updatePrivacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePrivacyPreferences")
    @ResponseWrapper(localName = "updatePrivacyPreferencesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePrivacyPreferencesResponse")
    public void updatePrivacyPreferences(
        @WebParam(name = "privacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityPrivacyPreferencesType> privacyPreferences)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param externalId
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addExternalIdentifierToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddExternalIdentifierToEntity")
    @ResponseWrapper(localName = "addExternalIdentifierToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddExternalIdentifierToEntityResponse")
    public void addExternalIdentifierToEntity(
        @WebParam(name = "externalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityExternalIdentifierType> externalId)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param principalIds
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.PrincipalType>
     */
    @WebMethod
    @WebResult(name = "ret", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getPrincipals", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipals")
    @ResponseWrapper(localName = "getPrincipalsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsResponse")
    public List<PrincipalType> getPrincipals(
        @WebParam(name = "principalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        List<String> principalIds);

    /**
     * 
     * @param entityTypeContactInfo
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addEntityTypeContactInfoToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEntityTypeContactInfoToEntity")
    @ResponseWrapper(localName = "addEntityTypeContactInfoToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEntityTypeContactInfoToEntityResponse")
    public void addEntityTypeContactInfoToEntity(
        @WebParam(name = "entityTypeContactInfo", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityTypeContactInfoType> entityTypeContactInfo)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param employment
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addEmploymentToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmploymentToEntity")
    @ResponseWrapper(localName = "addEmploymentToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmploymentToEntityResponse")
    public void addEmploymentToEntity(
        @WebParam(name = "employment", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityEmploymentType> employment)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityEmailType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "email", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateEmail", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmail")
    @ResponseWrapper(localName = "inactivateEmailResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmailResponse")
    public EntityEmailType inactivateEmail(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param bioDemographics
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateBioDemographics", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateBioDemographics")
    @ResponseWrapper(localName = "updateBioDemographicsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateBioDemographicsResponse")
    public void updateBioDemographics(
        @WebParam(name = "bioDemographics", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityBioDemographicsType> bioDemographics)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param phone
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updatePhone", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePhone")
    @ResponseWrapper(localName = "updatePhoneResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePhoneResponse")
    public void updatePhone(
        @WebParam(name = "phone", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityPhoneType> phone)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param visa
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateVisa", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateVisa")
    @ResponseWrapper(localName = "updateVisaResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateVisaResponse")
    public void updateVisa(
        @WebParam(name = "visa", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityVisaType> visa)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllCitizenshipStatuses", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllCitizenshipStatuses")
    @ResponseWrapper(localName = "findAllCitizenshipStatusesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllCitizenshipStatusesResponse")
    public List<CodedAttributeType> findAllCitizenshipStatuses();

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllEmploymentTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentTypes")
    @ResponseWrapper(localName = "findAllEmploymentTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentTypesResponse")
    public List<CodedAttributeType> findAllEmploymentTypes();

    /**
     * 
     * @param ethnicity
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateEthnicity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEthnicity")
    @ResponseWrapper(localName = "updateEthnicityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEthnicityResponse")
    public void updateEthnicity(
        @WebParam(name = "ethnicity", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityEthnicityType> ethnicity)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param name
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateName")
    @ResponseWrapper(localName = "updateNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateNameResponse")
    public void updateName(
        @WebParam(name = "name", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityNameType> name)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityPrivacyPreferencesType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "privacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityPrivacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityPrivacyPreferences")
    @ResponseWrapper(localName = "getEntityPrivacyPreferencesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityPrivacyPreferencesResponse")
    public EntityPrivacyPreferencesType getEntityPrivacyPreferences(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param address
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addAddressToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAddressToEntity")
    @ResponseWrapper(localName = "addAddressToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAddressToEntityResponse")
    public void addAddressToEntity(
        @WebParam(name = "address", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityAddressType> address)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param employeeId
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityByEmployeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityByEmployeeId")
    @ResponseWrapper(localName = "getEntityByEmployeeIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityByEmployeeIdResponse")
    public EntityType getEntityByEmployeeId(
        @WebParam(name = "employeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String employeeId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param citizenship
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addCitizenshipToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddCitizenshipToEntity")
    @ResponseWrapper(localName = "addCitizenshipToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddCitizenshipToEntityResponse")
    public void addCitizenshipToEntity(
        @WebParam(name = "citizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityCitizenshipType> citizenship)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param affiliation
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateAffiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAffiliation")
    @ResponseWrapper(localName = "updateAffiliationResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAffiliationResponse")
    public void updateAffiliation(
        @WebParam(name = "affiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityAffiliationType> affiliation)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param bioDemographics
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addBioDemographicsToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddBioDemographicsToEntity")
    @ResponseWrapper(localName = "addBioDemographicsToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddBioDemographicsToEntityResponse")
    public void addBioDemographicsToEntity(
        @WebParam(name = "bioDemographics", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityBioDemographicsType> bioDemographics)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param principalName
     * @param password
     * @return
     *     returns org.kuali.rice.kim.v2_0.PrincipalType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getPrincipalByPrincipalNameAndPassword", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalByPrincipalNameAndPassword")
    @ResponseWrapper(localName = "getPrincipalByPrincipalNameAndPasswordResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalByPrincipalNameAndPasswordResponse")
    public PrincipalType getPrincipalByPrincipalNameAndPassword(
        @WebParam(name = "principalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalName,
        @WebParam(name = "password", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String password)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllEmploymentStatuses", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentStatuses")
    @ResponseWrapper(localName = "findAllEmploymentStatusesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentStatusesResponse")
    public List<CodedAttributeType> findAllEmploymentStatuses();

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllPhoneTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllPhoneTypes")
    @ResponseWrapper(localName = "findAllPhoneTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllPhoneTypesResponse")
    public List<CodedAttributeType> findAllPhoneTypes();

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityDefaultType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entityDefault", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityDefault", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefault")
    @ResponseWrapper(localName = "getEntityDefaultResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefaultResponse")
    public EntityDefaultType getEntityDefault(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.PrincipalType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getPrincipal", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipal")
    @ResponseWrapper(localName = "getPrincipalResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalResponse")
    public PrincipalType getPrincipal(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param employeeId
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityDefaultType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entityDefault", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityDefaultByEmployeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefaultByEmployeeId")
    @ResponseWrapper(localName = "getEntityDefaultByEmployeeIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityDefaultByEmployeeIdResponse")
    public EntityDefaultType getEntityDefaultByEmployeeId(
        @WebParam(name = "employeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String employeeId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllEmailTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmailTypes")
    @ResponseWrapper(localName = "findAllEmailTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmailTypesResponse")
    public List<CodedAttributeType> findAllEmailTypes();

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEntityByPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityByPrincipalId")
    @ResponseWrapper(localName = "getEntityByPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityByPrincipalIdResponse")
    public EntityType getEntityByPrincipalId(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param entityTypeContactInfo
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "updateEntityTypeContactInfo", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEntityTypeContactInfo")
    @ResponseWrapper(localName = "updateEntityTypeContactInfoResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEntityTypeContactInfoResponse")
    public void updateEntityTypeContactInfo(
        @WebParam(name = "entityTypeContactInfo", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityTypeContactInfoType> entityTypeContactInfo)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param principal
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addPrincipalToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrincipalToEntity")
    @ResponseWrapper(localName = "addPrincipalToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrincipalToEntityResponse")
    public void addPrincipalToEntity(
        @WebParam(name = "principal", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<PrincipalType> principal)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.EntityExternalIdentifierTypeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllExternalIdentifierTypeTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllExternalIdentifierTypeTypes")
    @ResponseWrapper(localName = "findAllExternalIdentifierTypeTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllExternalIdentifierTypeTypesResponse")
    public List<EntityExternalIdentifierTypeType> findAllExternalIdentifierTypeTypes();

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "entity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivateEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEntity")
    @ResponseWrapper(localName = "inactivateEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEntityResponse")
    public EntityType inactivateEntity(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param code
     * @return
     *     returns org.kuali.rice.kim.v2_0.CodedAttributeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getEmploymentStatus", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentStatus")
    @ResponseWrapper(localName = "getEmploymentStatusResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentStatusResponse")
    public CodedAttributeType getEmploymentStatus(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.kuali.rice.kim.v2_0.EntityPhoneType
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "phone", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "inactivatePhone", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePhone")
    @ResponseWrapper(localName = "inactivatePhoneResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePhoneResponse")
    public EntityPhoneType inactivatePhone(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String id)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param entity
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "createEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.CreateEntity")
    @ResponseWrapper(localName = "createEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.CreateEntityResponse")
    public void createEntity(
        @WebParam(name = "entity", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityType> entity)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType>
     */
    @WebMethod
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "findAllEntityTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEntityTypes")
    @ResponseWrapper(localName = "findAllEntityTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEntityTypesResponse")
    public List<CodedAttributeType> findAllEntityTypes();

    /**
     * 
     * @param phone
     * @throws RiceIllegalStateException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "addPhoneToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPhoneToEntity")
    @ResponseWrapper(localName = "addPhoneToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPhoneToEntityResponse")
    public void addPhoneToEntity(
        @WebParam(name = "phone", targetNamespace = "http://rice.kuali.org/kim/v2_0", mode = WebParam.Mode.INOUT)
        Holder<EntityPhoneType> phone)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

}
