
package org.kuali.rice.kim.v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "roleService", targetNamespace = "http://rice.kuali.org/kim/v2_0", wsdlLocation = "http://demo.rice.kuali.org/remoting/soap/kim/v2_0/roleService?wsdl")
public class RoleService_Service
    extends Service
{

    private final static URL ROLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.kuali.rice.kim.v2_0.RoleService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.kuali.rice.kim.v2_0.RoleService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://demo.rice.kuali.org/remoting/soap/kim/v2_0/roleService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://demo.rice.kuali.org/remoting/soap/kim/v2_0/roleService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ROLESERVICE_WSDL_LOCATION = url;
    }

    public RoleService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public RoleService_Service(String baseUrl) throws MalformedURLException {
      super(new URL(baseUrl + "/remoting/soap/kim/v2_0/roleService?wsdl"), new QName("http://rice.kuali.org/kim/v2_0", "roleService"));
    }

    public RoleService_Service() {
        super(ROLESERVICE_WSDL_LOCATION, new QName("http://rice.kuali.org/kim/v2_0", "roleService"));
    }

    /**
     * 
     * @return
     *     returns RoleService
     */
    @WebEndpoint(name = "roleServicePort")
    public RoleService getRoleServicePort() {
        return super.getPort(new QName("http://rice.kuali.org/kim/v2_0", "roleServicePort"), RoleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleService
     */
    @WebEndpoint(name = "roleServicePort")
    public RoleService getRoleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rice.kuali.org/kim/v2_0", "roleServicePort"), RoleService.class, features);
    }

}
