
package org.kuali.rice.ken.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sendNotificationService", targetNamespace = "http://rice.kuali.org/ken/v2_0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.kuali.rice.ken.v2_0.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface SendNotificationService {


    /**
     * 
     * @param message
     * @return
     *     returns org.kuali.rice.ken.v2_0.NotificationResponseType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://rice.kuali.org/ken/v2_0", partName = "response")
    public NotificationResponseType invoke(
        @WebParam(name = "message", targetNamespace = "http://rice.kuali.org/ken/v2_0", partName = "message")
        String message)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param sendNotification
     * @return
     *     returns org.kuali.rice.ken.v2_0.NotificationResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://rice.kuali.org/ken/v2_0", partName = "response")
    public NotificationResponseType sendNotification(
        @WebParam(name = "sendNotification", targetNamespace = "http://rice.kuali.org/ken/v2_0", partName = "sendNotification")
        NotificationType sendNotification);

}
