
package org.kuali.rice.location.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.kuali.rice.core.v2_0.QueryByCriteriaType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PostalCodeService", targetNamespace = "http://rice.kuali.org/location/v2_0")
@XmlSeeAlso({
    org.kuali.rice.location.v2_0.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface PostalCodeService {


    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.location.v2_0.PostalCodeQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/location/v2_0")
    @RequestWrapper(localName = "findPostalCodes", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindPostalCodes")
    @ResponseWrapper(localName = "findPostalCodesResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindPostalCodesResponse")
    public PostalCodeQueryResultsType findPostalCodes(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/location/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param countryCode
     * @return
     *     returns org.kuali.rice.location.v2_0.FindAllPostalCodesInCountryResponse.PostalCodes
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "postalCodes", targetNamespace = "http://rice.kuali.org/location/v2_0")
    @RequestWrapper(localName = "findAllPostalCodesInCountry", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllPostalCodesInCountry")
    @ResponseWrapper(localName = "findAllPostalCodesInCountryResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllPostalCodesInCountryResponse")
    public org.kuali.rice.location.v2_0.FindAllPostalCodesInCountryResponse.PostalCodes findAllPostalCodesInCountry(
        @WebParam(name = "countryCode", targetNamespace = "http://rice.kuali.org/location/v2_0")
        String countryCode)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param countryCode
     * @param code
     * @return
     *     returns org.kuali.rice.location.v2_0.PostalCodeType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "postalCode", targetNamespace = "http://rice.kuali.org/location/v2_0")
    @RequestWrapper(localName = "getPostalCode", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.GetPostalCode")
    @ResponseWrapper(localName = "getPostalCodeResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.GetPostalCodeResponse")
    public PostalCodeType getPostalCode(
        @WebParam(name = "countryCode", targetNamespace = "http://rice.kuali.org/location/v2_0")
        String countryCode,
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/location/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

}
