
package org.kuali.rice.location.v2_0;

import javax.xml.ws.WebFault;
import org.kuali.rice.core.v2_0.IllegalStateFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "IllegalStateFault", targetNamespace = "http://rice.kuali.org/core/v2_0")
public class RiceIllegalStateException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IllegalStateFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RiceIllegalStateException(String message, IllegalStateFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RiceIllegalStateException(String message, IllegalStateFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.kuali.rice.core.v2_0.IllegalStateFault
     */
    public IllegalStateFault getFaultInfo() {
        return faultInfo;
    }

}
