
package org.kuali.rice.location.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.kuali.rice.core.v2_0.QueryByCriteriaType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StateService", targetNamespace = "http://rice.kuali.org/location/v2_0")
@XmlSeeAlso({
    org.kuali.rice.core.v2_0.ObjectFactory.class,
    org.kuali.rice.location.v2_0.ObjectFactory.class
})
public interface StateService {


    /**
     * 
     * @param countryCode
     * @param code
     * @return
     *     returns org.kuali.rice.location.v2_0.StateType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "state", targetNamespace = "http://rice.kuali.org/location/v2_0")
    @RequestWrapper(localName = "getState", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.GetState")
    @ResponseWrapper(localName = "getStateResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.GetStateResponse")
    public StateType getState(
        @WebParam(name = "countryCode", targetNamespace = "http://rice.kuali.org/location/v2_0")
        String countryCode,
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/location/v2_0")
        String code)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param alternateCode
     * @return
     *     returns org.kuali.rice.location.v2_0.FindAllStatesInCountryByAltCodeResponse.States
     * @throws RiceIllegalArgumentException
     * @throws RiceIllegalStateException
     */
    @WebMethod
    @WebResult(name = "states", targetNamespace = "http://rice.kuali.org/location/v2_0")
    @RequestWrapper(localName = "findAllStatesInCountryByAltCode", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllStatesInCountryByAltCode")
    @ResponseWrapper(localName = "findAllStatesInCountryByAltCodeResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllStatesInCountryByAltCodeResponse")
    public org.kuali.rice.location.v2_0.FindAllStatesInCountryByAltCodeResponse.States findAllStatesInCountryByAltCode(
        @WebParam(name = "alternateCode", targetNamespace = "http://rice.kuali.org/location/v2_0")
        String alternateCode)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.location.v2_0.StateQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/location/v2_0")
    @RequestWrapper(localName = "findStates", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindStates")
    @ResponseWrapper(localName = "findStatesResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindStatesResponse")
    public StateQueryResultsType findStates(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/location/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param countryCode
     * @return
     *     returns org.kuali.rice.location.v2_0.FindAllStatesInCountryResponse.States
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "states", targetNamespace = "http://rice.kuali.org/location/v2_0")
    @RequestWrapper(localName = "findAllStatesInCountry", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllStatesInCountry")
    @ResponseWrapper(localName = "findAllStatesInCountryResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllStatesInCountryResponse")
    public org.kuali.rice.location.v2_0.FindAllStatesInCountryResponse.States findAllStatesInCountry(
        @WebParam(name = "countryCode", targetNamespace = "http://rice.kuali.org/location/v2_0")
        String countryCode)
        throws RiceIllegalArgumentException
    ;

}
