
package org.kuali.rice.kew.v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "actionListCustomizationHandlerService", targetNamespace = "http://rice.kuali.org/kew/v2_0", wsdlLocation = "http://demo.rice.kuali.org/remoting/soap/kew/v2_0/actionListCustomizationHandlerService?wsdl")
public class ActionListCustomizationHandlerService_Service
    extends Service
{

    private final static URL ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_EXCEPTION;
    private final static QName ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_QNAME = new QName("http://rice.kuali.org/kew/v2_0", "actionListCustomizationHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://demo.rice.kuali.org/remoting/soap/kew/v2_0/actionListCustomizationHandlerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_WSDL_LOCATION = url;
        ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_EXCEPTION = e;
    }

    public ActionListCustomizationHandlerService_Service() {
        super(__getWsdlLocation(), ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_QNAME);
    }

    public ActionListCustomizationHandlerService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_QNAME, features);
    }

    public ActionListCustomizationHandlerService_Service(URL wsdlLocation) {
        super(wsdlLocation, ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_QNAME);
    }

    public ActionListCustomizationHandlerService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_QNAME, features);
    }

    public ActionListCustomizationHandlerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActionListCustomizationHandlerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActionListCustomizationHandlerService
     */
    @WebEndpoint(name = "actionListCustomizationHandlerServicePort")
    public ActionListCustomizationHandlerService getActionListCustomizationHandlerServicePort() {
        return super.getPort(new QName("http://rice.kuali.org/kew/v2_0", "actionListCustomizationHandlerServicePort"), ActionListCustomizationHandlerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActionListCustomizationHandlerService
     */
    @WebEndpoint(name = "actionListCustomizationHandlerServicePort")
    public ActionListCustomizationHandlerService getActionListCustomizationHandlerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rice.kuali.org/kew/v2_0", "actionListCustomizationHandlerServicePort"), ActionListCustomizationHandlerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_EXCEPTION!= null) {
            throw ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_EXCEPTION;
        }
        return ACTIONLISTCUSTOMIZATIONHANDLERSERVICE_WSDL_LOCATION;
    }

}
