
package org.kuali.rice.kew.v2_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "actionListService", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.kew.v2_0.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface ActionListService {


    /**
     * 
     * @param documentId
     * @return
     *     returns org.kuali.rice.kew.v2_0.GetAllActionItemsResponse.ActionItems
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "actionItems", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getAllActionItems", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetAllActionItems")
    @ResponseWrapper(localName = "getAllActionItemsResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetAllActionItemsResponse")
    public org.kuali.rice.kew.v2_0.GetAllActionItemsResponse.ActionItems getAllActionItems(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param actionRequestedCodes
     * @param documentId
     * @return
     *     returns org.kuali.rice.kew.v2_0.GetActionItemsResponse.ActionItems
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "actionItems", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getActionItems", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetActionItems")
    @ResponseWrapper(localName = "getActionItemsResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetActionItemsResponse")
    public org.kuali.rice.kew.v2_0.GetActionItemsResponse.ActionItems getActionItems(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "actionRequestedCodes", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        List<String> actionRequestedCodes)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns java.lang.Integer
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "userActionItemCount", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getUserActionItemCount", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetUserActionItemCount")
    @ResponseWrapper(localName = "getUserActionItemCountResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetUserActionItemCountResponse")
    public Integer getUserActionItemCount(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kew.v2_0.GetActionItemsForPrincipalResponse.ActionItems
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "actionItems", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getActionItemsForPrincipal", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetActionItemsForPrincipal")
    @ResponseWrapper(localName = "getActionItemsForPrincipalResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetActionItemsForPrincipalResponse")
    public org.kuali.rice.kew.v2_0.GetActionItemsForPrincipalResponse.ActionItems getActionItemsForPrincipal(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

}
