
package org.kuali.rice.kew.v2_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "actionListCustomizationHandlerService", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.kew.v2_0.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface ActionListCustomizationHandlerService {


    /**
     * 
     * @param principalId
     * @param actionItems
     * @return
     *     returns org.kuali.rice.kew.v2_0.CustomizeActionListResponse.ActionListCustomizations
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "actionListCustomizations", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "customizeActionList", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CustomizeActionList")
    @ResponseWrapper(localName = "customizeActionListResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CustomizeActionListResponse")
    public org.kuali.rice.kew.v2_0.CustomizeActionListResponse.ActionListCustomizations customizeActionList(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId,
        @WebParam(name = "actionItems", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        List<ActionItemType> actionItems)
        throws RiceIllegalArgumentException
    ;

}
