
package org.kuali.rice.kew.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "documentOrchestrationQueue", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.kew.v2_0.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface DocumentOrchestrationQueue {


    /**
     * 
     * @param principalId
     * @param documentProcessingOptions
     * @param orchestrationConfig
     * @param documentId
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "orchestrateDocument", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.OrchestrateDocument")
    @ResponseWrapper(localName = "orchestrateDocumentResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.OrchestrateDocumentResponse")
    public void orchestrateDocument(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId,
        @WebParam(name = "orchestrationConfig", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        OrchestrationConfigType orchestrationConfig,
        @WebParam(name = "documentProcessingOptions", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentProcessingOptionsType documentProcessingOptions)
        throws RiceIllegalArgumentException
    ;

}
