
package org.kuali.rice.kew.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "documentRefreshQueue", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.core.v2_0.ObjectFactory.class,
    org.kuali.rice.kew.v2_0.ObjectFactory.class
})
public interface DocumentRefreshQueue {


    /**
     * 
     * @param documentId
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "refreshDocument", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RefreshDocument")
    @ResponseWrapper(localName = "refreshDocumentResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RefreshDocumentResponse")
    public void refreshDocument(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId)
        throws RiceIllegalArgumentException
    ;

}
