
package org.kuali.rice.kew.v2_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "IllegalDocumentTypeException", targetNamespace = "http://rice.kuali.org/kew/v2_0")
public class IllegalDocumentTypeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IllegalDocumentTypeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IllegalDocumentTypeException_Exception(String message, IllegalDocumentTypeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IllegalDocumentTypeException_Exception(String message, IllegalDocumentTypeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.kuali.rice.kew.v2_0.IllegalDocumentTypeException
     */
    public IllegalDocumentTypeException getFaultInfo() {
        return faultInfo;
    }

}
