
package org.kuali.rice.kew.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "noteService", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.core.v2_0.ObjectFactory.class,
    org.kuali.rice.kew.v2_0.ObjectFactory.class
})
public interface NoteService {


    /**
     * 
     * @param noteId
     * @return
     *     returns org.kuali.rice.kew.v2_0.NoteType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "note", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "deleteNote", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DeleteNote")
    @ResponseWrapper(localName = "deleteNoteResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DeleteNoteResponse")
    public NoteType deleteNote(
        @WebParam(name = "noteId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String noteId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param documentId
     * @return
     *     returns org.kuali.rice.kew.v2_0.GetNotesResponse.Notes
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "notes", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getNotes", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetNotes")
    @ResponseWrapper(localName = "getNotesResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetNotesResponse")
    public org.kuali.rice.kew.v2_0.GetNotesResponse.Notes getNotes(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param noteId
     * @return
     *     returns org.kuali.rice.kew.v2_0.NoteType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "note", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getNote", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetNote")
    @ResponseWrapper(localName = "getNoteResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetNoteResponse")
    public NoteType getNote(
        @WebParam(name = "noteId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String noteId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param note
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.UpdateResponse")
    public void update(
        @WebParam(name = "note", targetNamespace = "http://rice.kuali.org/kew/v2_0", mode = WebParam.Mode.INOUT)
        Holder<NoteType> note)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param note
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "createNote", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CreateNote")
    @ResponseWrapper(localName = "createNoteResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CreateNoteResponse")
    public void createNote(
        @WebParam(name = "note", targetNamespace = "http://rice.kuali.org/kew/v2_0", mode = WebParam.Mode.INOUT)
        Holder<NoteType> note)
        throws RiceIllegalArgumentException
    ;

}
