
package org.kuali.rice.kew.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "peopleFlowService", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.kew.v2_0.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface PeopleFlowService {


    /**
     * 
     * @param peopleFlowId
     * @return
     *     returns org.kuali.rice.kew.v2_0.PeopleFlowDefinitionType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "peopleFlow", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getPeopleFlow", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPeopleFlow")
    @ResponseWrapper(localName = "getPeopleFlowResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPeopleFlowResponse")
    public PeopleFlowDefinitionType getPeopleFlow(
        @WebParam(name = "peopleFlowId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String peopleFlowId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param name
     * @param namespaceCode
     * @return
     *     returns org.kuali.rice.kew.v2_0.PeopleFlowDefinitionType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "peopleFlow", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getPeopleFlowByName", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPeopleFlowByName")
    @ResponseWrapper(localName = "getPeopleFlowByNameResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPeopleFlowByNameResponse")
    public PeopleFlowDefinitionType getPeopleFlowByName(
        @WebParam(name = "namespaceCode", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String namespaceCode,
        @WebParam(name = "name", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String name)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param peopleFlow
     * @throws RiceIllegalArgumentException
     * @throws RiceIllegalStateException
     */
    @WebMethod
    @RequestWrapper(localName = "createPeopleFlow", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CreatePeopleFlow")
    @ResponseWrapper(localName = "createPeopleFlowResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CreatePeopleFlowResponse")
    public void createPeopleFlow(
        @WebParam(name = "peopleFlow", targetNamespace = "http://rice.kuali.org/kew/v2_0", mode = WebParam.Mode.INOUT)
        Holder<PeopleFlowDefinitionType> peopleFlow)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param peopleFlow
     * @throws RiceIllegalArgumentException
     * @throws RiceIllegalStateException
     */
    @WebMethod
    @RequestWrapper(localName = "updatePeopleFlow", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.UpdatePeopleFlow")
    @ResponseWrapper(localName = "updatePeopleFlowResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.UpdatePeopleFlowResponse")
    public void updatePeopleFlow(
        @WebParam(name = "peopleFlow", targetNamespace = "http://rice.kuali.org/kew/v2_0", mode = WebParam.Mode.INOUT)
        Holder<PeopleFlowDefinitionType> peopleFlow)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

}
