
package org.kuali.rice.kew.v2_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.kuali.rice.core.v2_0.StringMapEntryListType;
import org.kuali.rice.kim.v2_0.PermissionType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "permissionTypeService", targetNamespace = "http://rice.kuali.org/kim/v2_0")
@XmlSeeAlso({
    org.kuali.rice.core.v2_0.ObjectFactory.class,
    org.kuali.rice.kim.v2_0.ObjectFactory.class
})
public interface PermissionTypeService {


    /**
     * 
     * @param oldAttributes
     * @param newAttributes
     * @param kimTypeId
     * @return
     *     returns org.kuali.rice.kim.v2_0.ValidateUniqueAttributesResponse.AttributeErrors
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "attributeErrors", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "validateUniqueAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateUniqueAttributes")
    @ResponseWrapper(localName = "validateUniqueAttributesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateUniqueAttributesResponse")
    public org.kuali.rice.kim.v2_0.ValidateUniqueAttributesResponse.AttributeErrors validateUniqueAttributes(
        @WebParam(name = "kimTypeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String kimTypeId,
        @WebParam(name = "newAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType newAttributes,
        @WebParam(name = "oldAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType oldAttributes)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param requestedDetails
     * @param permissions
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetMatchingPermissionsResponse.Permissions
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "permissions", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getMatchingPermissions", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMatchingPermissions")
    @ResponseWrapper(localName = "getMatchingPermissionsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetMatchingPermissionsResponse")
    public org.kuali.rice.kim.v2_0.GetMatchingPermissionsResponse.Permissions getMatchingPermissions(
        @WebParam(name = "requestedDetails", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType requestedDetails,
        @WebParam(name = "permissions", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        List<PermissionType> permissions)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param oldAttributes
     * @param newAttributes
     * @param kimTypeId
     * @return
     *     returns org.kuali.rice.kim.v2_0.ValidateAttributesAgainstExistingResponse.AttributeErrors
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "attributeErrors", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "validateAttributesAgainstExisting", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateAttributesAgainstExisting")
    @ResponseWrapper(localName = "validateAttributesAgainstExistingResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateAttributesAgainstExistingResponse")
    public org.kuali.rice.kim.v2_0.ValidateAttributesAgainstExistingResponse.AttributeErrors validateAttributesAgainstExisting(
        @WebParam(name = "kimTypeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String kimTypeId,
        @WebParam(name = "newAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType newAttributes,
        @WebParam(name = "oldAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType oldAttributes)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "name", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getWorkflowDocumentTypeName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetWorkflowDocumentTypeName")
    @ResponseWrapper(localName = "getWorkflowDocumentTypeNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetWorkflowDocumentTypeNameResponse")
    public String getWorkflowDocumentTypeName();

    /**
     * 
     * @param nodeName
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetWorkflowRoutingAttributesResponse.AttributeNames
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "attributeNames", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getWorkflowRoutingAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetWorkflowRoutingAttributes")
    @ResponseWrapper(localName = "getWorkflowRoutingAttributesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetWorkflowRoutingAttributesResponse")
    public org.kuali.rice.kim.v2_0.GetWorkflowRoutingAttributesResponse.AttributeNames getWorkflowRoutingAttributes(
        @WebParam(name = "nodeName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String nodeName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param kimTypeId
     * @return
     *     returns org.kuali.rice.kim.v2_0.GetAttributeDefinitionsResponse.KimAttributeFields
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "kimAttributeFields", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "getAttributeDefinitions", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAttributeDefinitions")
    @ResponseWrapper(localName = "getAttributeDefinitionsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAttributeDefinitionsResponse")
    public org.kuali.rice.kim.v2_0.GetAttributeDefinitionsResponse.KimAttributeFields getAttributeDefinitions(
        @WebParam(name = "kimTypeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String kimTypeId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param originalAttributes
     * @param newAttributes
     * @param kimTypeId
     * @return
     *     returns org.kuali.rice.kim.v2_0.ValidateUnmodifiableAttributesResponse.AttributeErrors
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "attributeErrors", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "validateUnmodifiableAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateUnmodifiableAttributes")
    @ResponseWrapper(localName = "validateUnmodifiableAttributesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateUnmodifiableAttributesResponse")
    public org.kuali.rice.kim.v2_0.ValidateUnmodifiableAttributesResponse.AttributeErrors validateUnmodifiableAttributes(
        @WebParam(name = "kimTypeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String kimTypeId,
        @WebParam(name = "originalAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType originalAttributes,
        @WebParam(name = "newAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType newAttributes)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param attributes
     * @param kimTypeId
     * @return
     *     returns org.kuali.rice.kim.v2_0.ValidateAttributesResponse.AttributeErrors
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "attributeErrors", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    @RequestWrapper(localName = "validateAttributes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateAttributes")
    @ResponseWrapper(localName = "validateAttributesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.ValidateAttributesResponse")
    public org.kuali.rice.kim.v2_0.ValidateAttributesResponse.AttributeErrors validateAttributes(
        @WebParam(name = "kimTypeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        String kimTypeId,
        @WebParam(name = "attributes", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        StringMapEntryListType attributes)
        throws RiceIllegalArgumentException
    ;

}
