
package org.kuali.rice.kew.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "preferencesService", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.core.v2_0.ObjectFactory.class,
    org.kuali.rice.kew.v2_0.ObjectFactory.class
})
public interface PreferencesService {


    /**
     * 
     * @param principalId
     * @return
     *     returns org.kuali.rice.kew.v2_0.PreferencesType
     */
    @WebMethod
    @WebResult(name = "preferences", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getPreferences", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPreferences")
    @ResponseWrapper(localName = "getPreferencesResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPreferencesResponse")
    public PreferencesType getPreferences(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId);

    /**
     * 
     * @param principalId
     * @param preferences
     */
    @WebMethod
    @RequestWrapper(localName = "savePreferences", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SavePreferences")
    @ResponseWrapper(localName = "savePreferencesResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SavePreferencesResponse")
    public void savePreferences(
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId,
        @WebParam(name = "preferences", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        PreferencesType preferences);

}
