
package org.kuali.rice.kew.v2_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "workflowDocumentActionsService", targetNamespace = "http://rice.kuali.org/kew/v2_0")
@XmlSeeAlso({
    org.kuali.rice.kew.v2_0.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface WorkflowDocumentActionsService {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.AdHocToPrincipalResponse
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "adHocToPrincipalResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AdHocToPrincipalResponse adHocToPrincipal(
        @WebParam(name = "adHocToPrincipal", targetNamespace = "http://rice.kuali.org/kew/v2_0", partName = "parameters")
        Object parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "cancel", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Cancel")
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CancelResponse")
    public DocumentActionResultType cancel(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param lookFuture
     * @param principalId
     * @param documentId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "userInRouteLog", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "isUserInRouteLog", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsUserInRouteLog")
    @ResponseWrapper(localName = "isUserInRouteLogResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsUserInRouteLogResponse")
    public boolean isUserInRouteLog(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId,
        @WebParam(name = "lookFuture", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean lookFuture)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @param documentId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "finalApprover", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "isFinalApprover", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsFinalApprover")
    @ResponseWrapper(localName = "isFinalApproverResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsFinalApproverResponse")
    public boolean isFinalApprover(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param executePostProcessor
     * @param parameters
     * @param returnPoint
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "superUserReturnToPreviousNode", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserReturnToPreviousNode")
    @ResponseWrapper(localName = "superUserReturnToPreviousNodeResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserReturnToPreviousNodeResponse")
    public DocumentActionResultType superUserReturnToPreviousNode(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "executePostProcessor", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean executePostProcessor,
        @WebParam(name = "returnPoint", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        ReturnPointType returnPoint)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "disapprove", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Disapprove")
    @ResponseWrapper(localName = "disapproveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DisapproveResponse")
    public DocumentActionResultType disapprove(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param documentContentUpdate
     * @param initiatorPrincipalId
     * @param documentUpdate
     * @param documentTypeName
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentType
     * @throws IllegalDocumentTypeException_Exception
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "create", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CreateResponse")
    public DocumentType create(
        @WebParam(name = "documentTypeName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentTypeName,
        @WebParam(name = "initiatorPrincipalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String initiatorPrincipalId,
        @WebParam(name = "documentUpdate", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentUpdateType documentUpdate,
        @WebParam(name = "documentContentUpdate", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentContentUpdateType documentContentUpdate)
        throws IllegalDocumentTypeException_Exception, InvalidActionTakenException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param executePostProcessor
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "superUserCancel", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserCancel")
    @ResponseWrapper(localName = "superUserCancelResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserCancelResponse")
    public DocumentActionResultType superUserCancel(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "executePostProcessor", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean executePostProcessor)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @param documentId
     * @return
     *     returns org.kuali.rice.kew.v2_0.RequestedActionsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "requestedActions", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "determineRequestedActions", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DetermineRequestedActions")
    @ResponseWrapper(localName = "determineRequestedActionsResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DetermineRequestedActionsResponse")
    public RequestedActionsType determineRequestedActions(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param docType
     * @param nodeName
     * @param docContent
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "routeNodeHasApproverActionRequest", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "routeNodeHasApproverActionRequest", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RouteNodeHasApproverActionRequest")
    @ResponseWrapper(localName = "routeNodeHasApproverActionRequestResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RouteNodeHasApproverActionRequestResponse")
    public boolean routeNodeHasApproverActionRequest(
        @WebParam(name = "docType", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String docType,
        @WebParam(name = "docContent", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String docContent,
        @WebParam(name = "nodeName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String nodeName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param nodeName
     * @param executePostProcessor
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "superUserNodeApprove", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserNodeApprove")
    @ResponseWrapper(localName = "superUserNodeApproveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserNodeApproveResponse")
    public DocumentActionResultType superUserNodeApprove(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "executePostProcessor", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean executePostProcessor,
        @WebParam(name = "nodeName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String nodeName)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "route", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Route")
    @ResponseWrapper(localName = "routeResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RouteResponse")
    public DocumentActionResultType route(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param roleName
     * @param documentId
     * @param qualifiedRoleNameLabel
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "reResolveRoleByDocumentId", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReResolveRoleByDocumentId")
    @ResponseWrapper(localName = "reResolveRoleByDocumentIdResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReResolveRoleByDocumentIdResponse")
    public void reResolveRoleByDocumentId(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "roleName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String roleName,
        @WebParam(name = "qualifiedRoleNameLabel", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String qualifiedRoleNameLabel)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param executePostProcessor
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "superUserBlanketApprove", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserBlanketApprove")
    @ResponseWrapper(localName = "superUserBlanketApproveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserBlanketApproveResponse")
    public DocumentActionResultType superUserBlanketApprove(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "executePostProcessor", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean executePostProcessor)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @param movePoint
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "move", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Move")
    @ResponseWrapper(localName = "moveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.MoveResponse")
    public DocumentActionResultType move(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "movePoint", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        MovePointType movePoint)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param executePostProcessor
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "superUserDisapprove", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserDisapprove")
    @ResponseWrapper(localName = "superUserDisapproveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserDisapproveResponse")
    public DocumentActionResultType superUserDisapprove(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "executePostProcessor", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean executePostProcessor)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param reportCriteria
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentDetailType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentDetail", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "executeSimulation", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ExecuteSimulation")
    @ResponseWrapper(localName = "executeSimulationResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ExecuteSimulationResponse")
    public DocumentDetailType executeSimulation(
        @WebParam(name = "reportCriteria", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        RoutingReportCriteriaType reportCriteria)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param revoke
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "revokeAdHocRequests", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RevokeAdHocRequests")
    @ResponseWrapper(localName = "revokeAdHocRequestsResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RevokeAdHocRequestsResponse")
    public DocumentActionResultType revokeAdHocRequests(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "revoke", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        AdHocRevokeType revoke)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param actionRequestId
     * @param executePostProcessor
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "superUserTakeRequestedAction", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserTakeRequestedAction")
    @ResponseWrapper(localName = "superUserTakeRequestedActionResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SuperUserTakeRequestedActionResponse")
    public DocumentActionResultType superUserTakeRequestedAction(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "executePostProcessor", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean executePostProcessor,
        @WebParam(name = "actionRequestId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String actionRequestId)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @param adHocToPrincipal
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod(operationName = "adHocToPrincipal_v2_1_3")
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "adHocToPrincipal_v2_1_3", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.AdHocToPrincipalV213")
    @ResponseWrapper(localName = "adHocToPrincipal_v2_1_3Response", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.AdHocToPrincipalV213Response")
    public DocumentActionResultType adHocToPrincipalV213(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "adHocToPrincipal", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        AdHocToPrincipalTypeV213 adHocToPrincipal)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "clearFyi", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ClearFyi")
    @ResponseWrapper(localName = "clearFyiResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ClearFyiResponse")
    public DocumentActionResultType clearFyi(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "save", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SaveResponse")
    public DocumentActionResultType save(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.AdHocToGroupResponse
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "adHocToGroupResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AdHocToGroupResponse adHocToGroup(
        @WebParam(name = "adHocToGroup", targetNamespace = "http://rice.kuali.org/kew/v2_0", partName = "parameters")
        Object parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "approve", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Approve")
    @ResponseWrapper(localName = "approveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ApproveResponse")
    public DocumentActionResultType approve(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param adHocToGroup
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod(operationName = "adHocToGroup_v2_1_3")
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "adHocToGroup_v2_1_3", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.AdHocToGroupV213")
    @ResponseWrapper(localName = "adHocToGroup_v2_1_3Response", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.AdHocToGroupV213Response")
    public DocumentActionResultType adHocToGroupV213(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "adHocToGroup", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        AdHocToGroupTypeV213 adHocToGroup)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param ignoreCurrentActionRequests
     * @param reportCriteria
     * @param actionRequestedCodes
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentWillHaveAtLeastOneActionRequest", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "documentWillHaveAtLeastOneActionRequest", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DocumentWillHaveAtLeastOneActionRequest")
    @ResponseWrapper(localName = "documentWillHaveAtLeastOneActionRequestResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DocumentWillHaveAtLeastOneActionRequestResponse")
    public boolean documentWillHaveAtLeastOneActionRequest(
        @WebParam(name = "reportCriteria", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        RoutingReportCriteriaType reportCriteria,
        @WebParam(name = "actionRequestedCodes", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        List<String> actionRequestedCodes,
        @WebParam(name = "ignoreCurrentActionRequests", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean ignoreCurrentActionRequests)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param actionRequestId
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "revokeAdHocRequestById", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RevokeAdHocRequestById")
    @ResponseWrapper(localName = "revokeAdHocRequestByIdResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RevokeAdHocRequestByIdResponse")
    public DocumentActionResultType revokeAdHocRequestById(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "actionRequestId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String actionRequestId)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @param documentId
     * @return
     *     returns org.kuali.rice.kew.v2_0.ValidActionsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "validActions", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "determineValidActions", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DetermineValidActions")
    @ResponseWrapper(localName = "determineValidActionsResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DetermineValidActionsResponse")
    public ValidActionsType determineValidActions(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param annotation
     * @param principalId
     * @param documentId
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "logAnnotation", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.LogAnnotation")
    @ResponseWrapper(localName = "logAnnotationResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.LogAnnotationResponse")
    public void logAnnotation(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId,
        @WebParam(name = "annotation", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String annotation)
        throws InvalidActionTakenException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "releaseGroupAuthority", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReleaseGroupAuthority")
    @ResponseWrapper(localName = "releaseGroupAuthorityResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReleaseGroupAuthorityResponse")
    public DocumentActionResultType releaseGroupAuthority(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String groupId)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param roleName
     * @param documentTypeName
     * @param qualifiedRoleNameLabel
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "reResolveRoleByDocTypeName", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReResolveRoleByDocTypeName")
    @ResponseWrapper(localName = "reResolveRoleByDocTypeNameResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReResolveRoleByDocTypeNameResponse")
    public void reResolveRoleByDocTypeName(
        @WebParam(name = "documentTypeName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentTypeName,
        @WebParam(name = "roleName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String roleName,
        @WebParam(name = "qualifiedRoleNameLabel", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String qualifiedRoleNameLabel)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "complete", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Complete")
    @ResponseWrapper(localName = "completeResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.CompleteResponse")
    public DocumentActionResultType complete(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @param documentId
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentType
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "delete", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.DeleteResponse")
    public DocumentType delete(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId)
        throws InvalidActionTakenException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param cancel
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "recall", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Recall")
    @ResponseWrapper(localName = "recallResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RecallResponse")
    public DocumentActionResultType recall(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "cancel", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean cancel)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "placeInExceptionRouting", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.PlaceInExceptionRouting")
    @ResponseWrapper(localName = "placeInExceptionRoutingResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.PlaceInExceptionRoutingResponse")
    public DocumentActionResultType placeInExceptionRouting(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param lookFuture
     * @param documentId
     * @return
     *     returns org.kuali.rice.kew.v2_0.GetPrincipalIdsInRouteLogResponse.PrincipalIds
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "principalIds", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "getPrincipalIdsInRouteLog", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPrincipalIdsInRouteLog")
    @ResponseWrapper(localName = "getPrincipalIdsInRouteLogResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.GetPrincipalIdsInRouteLogResponse")
    public org.kuali.rice.kew.v2_0.GetPrincipalIdsInRouteLogResponse.PrincipalIds getPrincipalIdsInRouteLog(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "lookFuture", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean lookFuture)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "revokeAllAdHocRequests", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RevokeAllAdHocRequests")
    @ResponseWrapper(localName = "revokeAllAdHocRequestsResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.RevokeAllAdHocRequestsResponse")
    public DocumentActionResultType revokeAllAdHocRequests(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "acknowledge", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.Acknowledge")
    @ResponseWrapper(localName = "acknowledgeResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.AcknowledgeResponse")
    public DocumentActionResultType acknowledge(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "blanketApprove", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.BlanketApprove")
    @ResponseWrapper(localName = "blanketApproveResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.BlanketApproveResponse")
    public DocumentActionResultType blanketApprove(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param definition
     * @return
     *     returns org.kuali.rice.kew.v2_0.ValidateWorkflowAttributeDefinitionResponse.ValidationErrors
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "validationErrors", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "validateWorkflowAttributeDefinition", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ValidateWorkflowAttributeDefinition")
    @ResponseWrapper(localName = "validateWorkflowAttributeDefinitionResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ValidateWorkflowAttributeDefinitionResponse")
    public org.kuali.rice.kew.v2_0.ValidateWorkflowAttributeDefinitionResponse.ValidationErrors validateWorkflowAttributeDefinition(
        @WebParam(name = "definition", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        WorkflowAttributeDefinitionType definition)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param principalId
     * @param nodeName
     * @param documentId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "lastApproverAtNode", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "isLastApproverAtNode", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsLastApproverAtNode")
    @ResponseWrapper(localName = "isLastApproverAtNodeResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsLastApproverAtNodeResponse")
    public boolean isLastApproverAtNode(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId,
        @WebParam(name = "nodeName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String nodeName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param lookFuture
     * @param principalId
     * @param flattenNodes
     * @param documentId
     * @return
     *     returns boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "userInRouteLogWithOptionalFlattening", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "isUserInRouteLogWithOptionalFlattening", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsUserInRouteLogWithOptionalFlattening")
    @ResponseWrapper(localName = "isUserInRouteLogWithOptionalFlatteningResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.IsUserInRouteLogWithOptionalFlatteningResponse")
    public boolean isUserInRouteLogWithOptionalFlattening(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId,
        @WebParam(name = "principalId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String principalId,
        @WebParam(name = "lookFuture", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean lookFuture,
        @WebParam(name = "flattenNodes", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        boolean flattenNodes)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "saveDocumentData", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SaveDocumentData")
    @ResponseWrapper(localName = "saveDocumentDataResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.SaveDocumentDataResponse")
    public DocumentActionResultType saveDocumentData(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param documentId
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "initiateIndexing", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.InitiateIndexing")
    @ResponseWrapper(localName = "initiateIndexingResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.InitiateIndexingResponse")
    public void initiateIndexing(
        @WebParam(name = "documentId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String documentId)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param nodeName
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "blanketApproveToNodes", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.BlanketApproveToNodes")
    @ResponseWrapper(localName = "blanketApproveToNodesResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.BlanketApproveToNodesResponse")
    public DocumentActionResultType blanketApproveToNodes(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "nodeName", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        List<String> nodeName)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameters
     * @param returnPoint
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "returnToPreviousNode", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReturnToPreviousNode")
    @ResponseWrapper(localName = "returnToPreviousNodeResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.ReturnToPreviousNodeResponse")
    public DocumentActionResultType returnToPreviousNode(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "returnPoint", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        ReturnPointType returnPoint)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

    /**
     * 
     * @param groupId
     * @param parameters
     * @return
     *     returns org.kuali.rice.kew.v2_0.DocumentActionResultType
     * @throws InvalidDocumentContentException
     * @throws InvalidActionTakenException
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "documentActionResult", targetNamespace = "http://rice.kuali.org/kew/v2_0")
    @RequestWrapper(localName = "takeGroupAuthority", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.TakeGroupAuthority")
    @ResponseWrapper(localName = "takeGroupAuthorityResponse", targetNamespace = "http://rice.kuali.org/kew/v2_0", className = "org.kuali.rice.kew.v2_0.TakeGroupAuthorityResponse")
    public DocumentActionResultType takeGroupAuthority(
        @WebParam(name = "parameters", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        DocumentActionParametersType parameters,
        @WebParam(name = "groupId", targetNamespace = "http://rice.kuali.org/kew/v2_0")
        String groupId)
        throws InvalidActionTakenException, InvalidDocumentContentException, RiceIllegalArgumentException
    ;

}
