
package org.kuali.rice.kew.v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "workflowDocumentActionsService", targetNamespace = "http://rice.kuali.org/kew/v2_0", wsdlLocation = "http://demo.rice.kuali.org/remoting/soap/kew/v2_0/workflowDocumentActionsService?wsdl")
public class WorkflowDocumentActionsService_Service
    extends Service
{

    private final static URL WORKFLOWDOCUMENTACTIONSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.kuali.rice.kew.v2_0.WorkflowDocumentActionsService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.kuali.rice.kew.v2_0.WorkflowDocumentActionsService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://demo.rice.kuali.org/remoting/soap/kew/v2_0/workflowDocumentActionsService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://demo.rice.kuali.org/remoting/soap/kew/v2_0/workflowDocumentActionsService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WORKFLOWDOCUMENTACTIONSSERVICE_WSDL_LOCATION = url;
    }

    public WorkflowDocumentActionsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkflowDocumentActionsService_Service() {
        super(WORKFLOWDOCUMENTACTIONSSERVICE_WSDL_LOCATION, new QName("http://rice.kuali.org/kew/v2_0", "workflowDocumentActionsService"));
    }

    /**
     * 
     * @return
     *     returns WorkflowDocumentActionsService
     */
    @WebEndpoint(name = "workflowDocumentActionsServicePort")
    public WorkflowDocumentActionsService getWorkflowDocumentActionsServicePort() {
        return super.getPort(new QName("http://rice.kuali.org/kew/v2_0", "workflowDocumentActionsServicePort"), WorkflowDocumentActionsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkflowDocumentActionsService
     */
    @WebEndpoint(name = "workflowDocumentActionsServicePort")
    public WorkflowDocumentActionsService getWorkflowDocumentActionsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rice.kuali.org/kew/v2_0", "workflowDocumentActionsServicePort"), WorkflowDocumentActionsService.class, features);
    }

}
