
package org.kuali.rice.core.v2_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CacheAdminService", targetNamespace = "http://cache.api.core.rice.kuali.org/")
@XmlSeeAlso({
    org.kuali.rice.core.api.cache.ObjectFactory.class,
    org.kuali.rice.core.v2_0.ObjectFactory.class
})
public interface CacheAdminService {


    /**
     * 
     * @param cacheTargets
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @RequestWrapper(localName = "flush", targetNamespace = "http://cache.api.core.rice.kuali.org/", className = "org.kuali.rice.core.api.cache.Flush")
    @ResponseWrapper(localName = "flushResponse", targetNamespace = "http://cache.api.core.rice.kuali.org/", className = "org.kuali.rice.core.api.cache.FlushResponse")
    public void flush(
        @WebParam(name = "cacheTargets", targetNamespace = "http://cache.api.core.rice.kuali.org/")
        List<CacheTargetType> cacheTargets)
        throws RiceIllegalArgumentException
    ;

}
