
package org.kuali.rice.core.v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "componentService", targetNamespace = "http://rice.kuali.org/core/v2_0", wsdlLocation = "http://demo.rice.kuali.org/remoting/soap/core/v2_0/componentService?wsdl")
public class ComponentService_Service
    extends Service
{

    private final static URL COMPONENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPONENTSERVICE_EXCEPTION;
    private final static QName COMPONENTSERVICE_QNAME = new QName("http://rice.kuali.org/core/v2_0", "componentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://demo.rice.kuali.org/remoting/soap/core/v2_0/componentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPONENTSERVICE_WSDL_LOCATION = url;
        COMPONENTSERVICE_EXCEPTION = e;
    }

    public ComponentService_Service() {
        super(__getWsdlLocation(), COMPONENTSERVICE_QNAME);
    }

    public ComponentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPONENTSERVICE_QNAME, features);
    }

    public ComponentService_Service(URL wsdlLocation) {
        super(wsdlLocation, COMPONENTSERVICE_QNAME);
    }

    public ComponentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPONENTSERVICE_QNAME, features);
    }

    public ComponentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComponentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ComponentService
     */
    @WebEndpoint(name = "componentServicePort")
    public ComponentService getComponentServicePort() {
        return super.getPort(new QName("http://rice.kuali.org/core/v2_0", "componentServicePort"), ComponentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComponentService
     */
    @WebEndpoint(name = "componentServicePort")
    public ComponentService getComponentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rice.kuali.org/core/v2_0", "componentServicePort"), ComponentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPONENTSERVICE_EXCEPTION!= null) {
            throw COMPONENTSERVICE_EXCEPTION;
        }
        return COMPONENTSERVICE_WSDL_LOCATION;
    }

}
