
package org.kuali.rice.core.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "parameterService", targetNamespace = "http://rice.kuali.org/core/v2_0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParameterService {


    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "value", targetNamespace = "http://rice.kuali.org/core/v2_0")
    @RequestWrapper(localName = "getParameterValueAsString", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameterValueAsString")
    @ResponseWrapper(localName = "getParameterValueAsStringResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameterValueAsStringResponse")
    public String getParameterValueAsString(
        @WebParam(name = "key", targetNamespace = "http://rice.kuali.org/core/v2_0")
        ParameterKeyType key)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameter
     * @throws RiceIllegalArgumentException
     * @throws RiceIllegalStateException
     */
    @WebMethod
    @RequestWrapper(localName = "createParameter", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.CreateParameter")
    @ResponseWrapper(localName = "createParameterResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.CreateParameterResponse")
    public void createParameter(
        @WebParam(name = "parameter", targetNamespace = "http://rice.kuali.org/core/v2_0", mode = WebParam.Mode.INOUT)
        Holder<ParameterType> parameter)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param subParameterName
     * @param key
     * @return
     *     returns org.kuali.rice.core.v2_0.GetSubParameterValuesAsStringResponse.Values
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "values", targetNamespace = "http://rice.kuali.org/core/v2_0")
    @RequestWrapper(localName = "getSubParameterValuesAsString", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetSubParameterValuesAsString")
    @ResponseWrapper(localName = "getSubParameterValuesAsStringResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetSubParameterValuesAsStringResponse")
    public org.kuali.rice.core.v2_0.GetSubParameterValuesAsStringResponse.Values getSubParameterValuesAsString(
        @WebParam(name = "key", targetNamespace = "http://rice.kuali.org/core/v2_0")
        ParameterKeyType key,
        @WebParam(name = "subParameterName", targetNamespace = "http://rice.kuali.org/core/v2_0")
        String subParameterName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param query
     * @return
     *     returns org.kuali.rice.core.v2_0.ParameterQueryResultsType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/core/v2_0")
    @RequestWrapper(localName = "findParameters", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.FindParameters")
    @ResponseWrapper(localName = "findParametersResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.FindParametersResponse")
    public ParameterQueryResultsType findParameters(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/core/v2_0")
        QueryByCriteriaType query)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param parameter
     * @throws RiceIllegalArgumentException
     * @throws RiceIllegalStateException
     */
    @WebMethod
    @RequestWrapper(localName = "updateParameter", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.UpdateParameter")
    @ResponseWrapper(localName = "updateParameterResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.UpdateParameterResponse")
    public void updateParameter(
        @WebParam(name = "parameter", targetNamespace = "http://rice.kuali.org/core/v2_0", mode = WebParam.Mode.INOUT)
        Holder<ParameterType> parameter)
        throws RiceIllegalArgumentException, RiceIllegalStateException
    ;

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.Boolean
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "value", targetNamespace = "http://rice.kuali.org/core/v2_0")
    @RequestWrapper(localName = "getParameterValueAsBoolean", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameterValueAsBoolean")
    @ResponseWrapper(localName = "getParameterValueAsBooleanResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameterValueAsBooleanResponse")
    public Boolean getParameterValueAsBoolean(
        @WebParam(name = "key", targetNamespace = "http://rice.kuali.org/core/v2_0")
        ParameterKeyType key)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param subParameterName
     * @param key
     * @return
     *     returns java.lang.String
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "value", targetNamespace = "http://rice.kuali.org/core/v2_0")
    @RequestWrapper(localName = "getSubParameterValueAsString", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetSubParameterValueAsString")
    @ResponseWrapper(localName = "getSubParameterValueAsStringResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetSubParameterValueAsStringResponse")
    public String getSubParameterValueAsString(
        @WebParam(name = "key", targetNamespace = "http://rice.kuali.org/core/v2_0")
        ParameterKeyType key,
        @WebParam(name = "subParameterName", targetNamespace = "http://rice.kuali.org/core/v2_0")
        String subParameterName)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param key
     * @return
     *     returns org.kuali.rice.core.v2_0.ParameterType
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "parameter", targetNamespace = "http://rice.kuali.org/core/v2_0")
    @RequestWrapper(localName = "getParameter", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameter")
    @ResponseWrapper(localName = "getParameterResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameterResponse")
    public ParameterType getParameter(
        @WebParam(name = "key", targetNamespace = "http://rice.kuali.org/core/v2_0")
        ParameterKeyType key)
        throws RiceIllegalArgumentException
    ;

    /**
     * 
     * @param key
     * @return
     *     returns org.kuali.rice.core.v2_0.GetParameterValuesAsStringResponse.Values
     * @throws RiceIllegalArgumentException
     */
    @WebMethod
    @WebResult(name = "values", targetNamespace = "http://rice.kuali.org/core/v2_0")
    @RequestWrapper(localName = "getParameterValuesAsString", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameterValuesAsString")
    @ResponseWrapper(localName = "getParameterValuesAsStringResponse", targetNamespace = "http://rice.kuali.org/core/v2_0", className = "org.kuali.rice.core.v2_0.GetParameterValuesAsStringResponse")
    public org.kuali.rice.core.v2_0.GetParameterValuesAsStringResponse.Values getParameterValuesAsString(
        @WebParam(name = "key", targetNamespace = "http://rice.kuali.org/core/v2_0")
        ParameterKeyType key)
        throws RiceIllegalArgumentException
    ;

}
